export {
  broadcastToAllToolWindows,
  closeMainWindow,
  closeWindow,
  consumePendingTool,
  consumePendingToolForWindow,
  createMainWindow,
  ensureHubWindow,
  ensureUnpinned,
  ensureUnpinnedForWindow,
  focusPinnedTool,
  forceQuitAllWindows,
  forceQuitWindow,
  getHubToolId,
  getHubWindow,
  getMainWindow,
  getPinState,
  getPinStateForWindow,
  getSession,
  getSessionFromWebContents,
  getSessionNavStack,
  hasPinnedPluginWindows,
  hideHubWindow,
  hideMainWindow,
  hideWindow,
  isHubVisibleWithUnpinnedPlugin,
  maximizeMainWindow,
  maximizeWindow,
  minimizeMainWindow,
  minimizeWindow,
  openToolInHub,
  setAlwaysOnTop,
  setAlwaysOnTopForWindow,
  setPendingTool,
  setSessionNavStack,
  setToolIconPathResolver,
  showMainWindow,
  showToolInWindow,
  syncTaskbarIcon,
  syncTaskbarIconForSession,
  togglePin,
  togglePinForWindow,
  type NavigateToolPayload,
  type PinState,
  type WindowSession
} from './window/windowSessionManager'
